apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: samfriedman-net-tls
spec:
  secretName: samfriedman-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: samfriedman.net
  dnsNames:
    - samfriedman.net
    - www.samfriedman.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - samfriedman.net
          - www.samfriedman.net
